# Docker Container for Ingress Llamfax Service
FROM jfloff/alpine-python:latest

ARG DBHOST="LFXMongo"
ENV DBHOST=${DBHOST}
ENV BUILDVER="1.07.1822"

ARG APIKEY
ENV APIKEY=${APIKEY}

USER root
RUN mkdir -p /llamafax/lib
# Imports App Dependancies
ADD app/ingress.py /llamafax/.
ADD app/lib/. /llamafax/lib/.

# Update and install Pip packages
RUN apk update && apk upgrade && pip3 install --upgrade pip
RUN pip3 install requests datetime pymongo

WORKDIR /llamafax

CMD python3 ingress.py